name: wevr_app
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  awesome_card: ^1.1.7
  build_runner: ^2.3.3
  carousel_slider: ^4.2.1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  easy_localization: ^3.0.1

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.1
  fluttertoast: ^8.1.3
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.3
  image_picker: ^0.8.6+2
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  retrofit: ^3.3.1
  retrofit_generator: ^4.2.0
  shared_preferences: ^2.0.17
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.9
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/home/
    - assets/images/reset_password/
    - assets/images/icons/
    - assets/images/logo/get_started.jpg
    - assets/images/personal_icons/
    - assets/images/change_lang/
    - assets/images/credit/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Light-BETA.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
